import claseCola as co

cola_1 = co.Cola()
print(cola_1.es_vacia())

cola_1.encolar(3)
cola_1.encolar(4)
cola_1.encolar(5)
cola_1.encolar(6)
cola_1.encolar(7)
cola_1.encolar(8)
cola_1.ver_cola()
# cola_1.tamano_cola()
# cola_1.obtener_cabezera()
# cola_1.obtener_final()
cola_1.mover_cabeza_al_final()
cola_1.ver_cola()
# cola_1.desencolar()
# cola_1.desencolar()
# cola_1.encolar(9)
# cola_1.encolar(10)
# cola_1.ver_cola()